module.exports = {
  content: [
    "./index.php",
    "./dashboard/**/*.php",
    "./activos/js/**/*.js"
  ],
  safelist: [
    // Clases existentes
    "backdrop-blur-lg",
    "backdrop-blur-sm", 
    "backdrop-blur-xl",
    "backdrop-blur-3xl",
    "text-white",
    "text-white/50",
    "text-white/60", 
    "text-white/70",
    "text-white/80",
    "hover:text-white/80",
    "hover:bg-white/90",
    "focus:ring-4",
    "focus:ring-white/30",
    "hover:scale-[1.02]",
    "active:scale-[0.98]",
    "bg-white/10",
    "bg-white/20",
    "bg-white/80",
    "bg-white/90",
    "bg-white/95",
    "border-white/20",
    "focus:border-white/40",
    "rounded-xl",
    "rounded-2xl",
    "rounded-3xl",
    "shadow-2xl",
    "shadow-xl",
    "shadow-lg",
    "shadow-md",
    "transition-all",
    "duration-300",
    "ease-out",
    "animation",
    "slideInUp",
    
    // Nuevas clases para el modal
    "bg-black/80",
    "text-gray-600",
    "text-gray-700", 
    "border-gray-200",
    "border-gray-300",
    "focus:border-purple-500",
    "focus:ring-purple-500/10",
    "border-green-500",
    "border-red-500",
    "ring-green-500/10",
    "ring-red-500/10",
    "text-red-500",
    "text-green-500", 
    "text-yellow-500",
    "hover:-translate-y-0.5",
    "hover:-translate-y-1",
    "active:translate-y-0",
    "hover:shadow-purple-500/40",
    "w-1/3",
    "w-2/3",
    "w-full",
    "pointer-events-none",
    "opacity-60",
    "opacity-80",
    "space-y-2",
    "space-y-6",
    "tracking-wide",
    "font-black",
    "font-bold",
    "font-medium",
    "font-semibold",
    "appearance-none",
    "cursor-pointer",
    "overflow-hidden",
    "animate-pulse"
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}